### ISSUE TITLE
Acrescentar matéria na seção "na mídia" - G1

### ISSUE THREAD

**Issue by tatianasb** [parlametria/parlametria-site#45]
Data: 08.dezembro.2019
Título: 'Parlametria': 90% dos deputados federais eleitos em 2018 receberam doações de empresários
Autor: -
Veículo: G1 Paraíba
Link: https://g1.globo.com/pb/paraiba/noticia/2019/12/08/parlametria-90percent-dos-deputados-federais-eleitos-em-2018-receberam-doacoes-de-empresarios.ghtml

**Comment by ArianeCamilo** [comment]
Postado!
