### ISSUE TITLE
Acrescentar matéria na seção "na mídia" - Gazeta do Povo

### ISSUE THREAD

**Issue by tatianasb** [parlametria/parlametria-site#46]
Data: 29.novembro.2019
Título: Ranking do bolsonarismo: saiba quais são os deputados mais governistas do Paraná
Autor: João Frey
Veículo: Gazeta do Povo
Link: https://www.gazetadopovo.com.br/vozes/joao-frey/deputados-governistas-parana/

**Comment by ArianeCamilo** [comment]
Postado!
