### ISSUE TITLE
Acrescentar matéria na seção "na mídia" - Gazeta do Povo (2)

### ISSUE THREAD

**Issue by tatianasb** [parlametria/parlametria-site#47]
Data: 28.novembro.2019
Título: Estudo mostra qual o senador do Paraná mais alinhado ao governo Bolsonaro
Autor: João Frey
Veículo: Gazeta do Povo
https://www.gazetadopovo.com.br/vozes/joao-frey/senadores-parana-alinhamento-governo/

**Comment by ArianeCamilo** [comment]
Postado
