### ISSUE TITLE
Acrescentar matéria na seção "na mídia" - O Globo

### ISSUE THREAD

**Issue by tatianasb** [parlametria/parlametria-site#48]
Data: 02.dezembro.2019
Título: Doações de empresários chegaram a 90% dos deputados, diz estudo
Autor: Maiá Menezes
Veículo: O Globo
https://oglobo.globo.com/brasil/doacoes-de-empresarios-chegaram-90-dos-deputados-diz-estudo-24112316

**Comment by ArianeCamilo** [comment]
Postado!
