### ISSUE TITLE
Acrescentar matéria na seção "na mídia" - Folha de S. Paulo

### ISSUE THREAD

**Issue by tatianasb** [parlametria/parlametria-site#50]
Data: 26.novembro.2019
Título: Cidadão encontra pelo menos 19 barreiras para acessar dados sobre Congresso
Autor: Mônica Bergamo
Veículo: Folha de S. Paulo
https://www1.folha.uol.com.br/colunas/monicabergamo/2019/11/cidadao-encontra-pelo-menos-19-barreiras-para-acessar-dados-sobre-congresso.shtml

**Comment by ArianeCamilo** [comment]
Postado!
